### ISSUE TITLE
NoSuchMethodError: org.apache.commons.codec.binary.Base64.decodeBase64

### ISSUE THREAD

**Issue by edwinvanelk** [mendix/EmailModuleWithTemplates#17]
When sending an email that has a base64 image in the template i get the following error (using Mendix 7.9.0, module 8.1.1):

java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.decodeBase64(Ljava/lang/String;)[B
	at emailtemplate.mail.Sender.send(Sender.java:95)
	at emailtemplate.mail.EmailModule.mail(EmailModule.java:141)
	at emailtemplate.actions.SendEmail.executeAction(SendEmail.java:163)
	at emailtemplate.actions.SendEmail.executeAction(SendEmail.java:1)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:50)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:76)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:55)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:55)
	at com.mendix.basis.actionmanagement.ActionManager$1.execute(ActionManager.java:186)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.java:191)
	at com.mendix.basis.component.InternalCore.execute(InternalCore.java:583)
	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:60)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)

**Comment by RoelandSalij** [comment]
Hi Edwin,
Do you mean in your own project or in this GitHub Repo project?
I tried the module in this repo and didn’t run into an issue. Can you share the reproduction steps?

Van: edwinvanelk [mailto:notifications@github.com]
Verzonden: donderdag 21 december 2017 15:20
Aan: mendix/EmailModuleWithTemplates <EmailModuleWithTemplates@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [mendix/EmailModuleWithTemplates] NoSuchMethodError: org.apache.commons.codec.binary.Base64.decodeBase64 (#17)


When sending an email that has a base64 image in the template i get the following error (using Mendix 7.9.0, module 8.1.1):

java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.decodeBase64(Ljava/lang/String;)[B
at emailtemplate.mail.Sender.send(Sender.java:95)
at emailtemplate.mail.EmailModule.mail(EmailModule.java:141)
at emailtemplate.actions.SendEmail.executeAction(SendEmail.java:163)
at emailtemplate.actions.SendEmail.executeAction(SendEmail.java:1)
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:50)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:76)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:55)
at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:55)
at com.mendix.basis.actionmanagement.ActionManager$1.execute(ActionManager.java:186)
at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.java:191)
at com.mendix.basis.component.InternalCore.execute(InternalCore.java:583)
at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:60)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)

**Comment by edwinvanelk** [comment]
In our own application.

I'm not able to export Mendix package to reproduce because of holiday right now.

However I have recorded the reproduction steps:
[steps.zip](https://github.com/mendix/EmailModuleWithTemplates/files/1580086/steps.zip)

**Comment by RoelandSalij** [comment]
Hi, can you list the files in the userlib folder of your project? I suspect something is conflicting there.

**Comment by edwinvanelk** [comment]
Contents of userlib folder:

antisamy-1.5.3.jar
antisamy-1.5.3.jar.CommunityCommons.RequiredLib
axiom-api-1.2.12.jar
axiom-api-1.2.12.jar.AppCloudServices.RequiredLib
bcpg-jdk15on-150.jar
bcpkix-jdk15on-150.jar
bcprov-jdk15on-150.jar
com.google.guava-14.0.1.jar
com.google.guava-14.0.1.jar.CommunityCommons.RequiredLib
com.springsource.org.apache.batik.css-1.7.0.jar
com.springsource.org.apache.batik.css-1.7.0.jar.CommunityCommons.RequiredLib
commons-codec-1.10.jar
commons-codec-1.10.jar.CommunityCommons.RequiredLib
commons-codec-1.10.jar.EmailTemplate.RequiredLib
commons-email-1.4.jar
commons-email-1.4.jar.EmailTemplate.RequiredLib
commons-httpclient-3.1.jar
commons-httpclient-3.1.jar.RestServices.RequiredLib
commons-io-2.3.jar
commons-io-2.3.jar.RequiredLib.Deeplink
commons-lang-2.5.jar
commons-lang-2.5.jar.AppCloudServices.RequiredLib
commons-logging-1.1.jar
commons-logging-1.1.jar.AppCloudServices.RequiredLib
guice-2.0.jar
guice-2.0.jar.AppCloudServices.RequiredLib
javax.mail-1.6.0.jar
javax.mail-1.6.0.jar.EmailTemplate.RequiredLib
jcifs-1.3.18.jar
jcifs-1.3.18.jar.RestServices.RequiredLib
jempbox-1.8.5.jar
jempbox-1.8.5.jar.CommunityCommons.RequiredLib
joda-time-2.9.6.jar
joda-time-2.9.6.jar.CommunityCommons.RequiredLib
nekohtml.jar
nekohtml.jar.CommunityCommons.RequiredLib
nekohtml.txt
openid4java-0.9.8.jar
openid4java-1.0.0.jar
openid4java-1.0.0.jar.AppCloudServices.RequiredLib
org.apache.commons.fileupload-1.2.1.jar
org.apache.commons.fileupload-1.2.1.jar.CommunityCommons.RequiredLib
org.apache.commons.io-2.3.0.jar
org.apache.commons.io-2.3.0.jar.CommunityCommons.RequiredLib
org.apache.commons.lang3.jar
org.apache.commons.lang3.jar.CommunityCommons.RequiredLib
org.apache.commons.lang3.jar.RequiredLib.Deeplink
org.apache.httpcomponents.httpclient-osgi.jar
org.apache.httpcomponents.httpclient-osgi.jar.AppCloudServices.RequiredLib
org.apache.httpcomponents.httpcore-osgi.jar
org.apache.httpcomponents.httpcore-osgi.jar.AppCloudServices.RequiredLib
org.apache.servicemix.bundles.batik.1.8_1.jar
org.apache.servicemix.bundles.batik.1.8_1.jar.CommunityCommons.RequiredLib
org.apache.servicemix.bundles.commons-codec-1.3.0.jar
pdfbox-app-2.0.3.jar
pdfbox-app-2.0.3.jar.CommunityCommons.RequiredLib
xerces.xercesImpl.2.8.1.jar
xerces.xercesImpl.2.8.1.jar.CommunityCommons.RequiredLib
xml-apis-ext.jar
xml-apis-ext.jar.CommunityCommons.RequiredLib

**Comment by edwinvanelk** [comment]
Seems to be a conflict with the org.apache.servicemix.bundles.commons-codec-1.3.0.jar file.

**Comment by edwinvanelk** [comment]
Tested in 7.18.1:

The file org.apache.servicemix.bundles.commons-codec-1.3.0.jar is not included in latest version of Encryption module (Encryption1.4.1) anymore.

Using EmailModuleWithTemplates with Encryption1.4.1 (and after removing userlib\org.apache.servicemix.bundles.commons-codec-1.3.0.jar) there are no errors anymore using template with included image(s).

**Comment by RoelandSalij** [comment]
Thanks for the feedback Edwin!
