### ISSUE TITLE
Unable to view Domain Model - Mendix v7.23.6

### ISSUE THREAD

**Issue by mkdaniels** [mendix/EmailModuleWithTemplates#29]
When trying to view the domain model we receive an error:
![image](https://user-images.githubusercontent.com/27896566/64277728-e9712700-ceff-11e9-9c24-91254c31b6c1.png)

The error seems to reference the painting of the domain model and, particularly, the associations.  I see the module is published in 7.13.1, possibly an issue due to the changing of how self-associations are visualized?

Here's the error:

> System.OverflowException: Overflow error.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawImage(Image image, Single x, Single y, Single width, Single height)
   at System.Drawing.Graphics.DrawImage(Image image, RectangleF rect)
   at Mendix.Modeler.DomainModels.AbstractAssociationView\`1.DrawCardinality(Graphics graphics, PointF middlePoint, CardinalityType type) in C:\jenkins-ci\workspace\AppStudio3.0-Build\modeler\Mendix.Modeler.Core.View\DomainModels\Associations\AbstractAssociationView.cs:line 153
   at Mendix.Modeler.DomainModels.AbstractAssociationView\`1.DrawCardinalities(Graphics graphics, TAssociation association, Point parentCardinalityPoint, Point childCardinalityPoint) in C:\jenkins-ci\workspace\AppStudio3.0-Build\modeler\Mendix.Modeler.Core.View\DomainModels\Associations\AbstractAssociationView.cs:line 93
   at Mendix.Modeler.DomainModels.AbstractAssociationView\`1.DrawAssociation(Graphics graphics, Point parentPoint, Point childPoint, Boolean isSelected, Boolean isReadOnly, Point parentCardinalityPoint, Point childCardinalityPoint) in C:\jenkins-ci\workspace\AppStudio3.0-Build\modeler\Mendix.Modeler.Core.View\DomainModels\Associations\AbstractAssociationView.cs:line 71
   at Mendix.Modeler.DomainModels.AssociationView.Paint(Graphics graphics) in C:\jenkins-ci\workspace\AppStudio3.0-Build\modeler\Mendix.Modeler.Core.View\DomainModels\Associations\AssociationView.cs:line 61
   at Mendix.Modeler.DomainModels.DomainModelView.Paint(Graphics graphics) in C:\jenkins-ci\workspace\AppStudio3.0-Build\modeler\Mendix.Modeler.Core.View\DomainModels\DomainModelView.cs:line 119
   at Mendix.Modeler.DomainModels.DomainModelEditor.DoPaint(PaintEventArgs e) in C:\jenkins-ci\workspace\AppStudio3.0-Build\modeler\Mendix.Modeler.Core.View\DomainModels\DomainModelEditor.cs:line 358
   at Mendix.Modeler.DomainModels.DomainModelEditor.canvas_Paint(Object sender, PaintEventArgs e) in C:\jenkins-ci\workspace\AppStudio3.0-Build\modeler\Mendix.Modeler.Core.View\DomainModels\DomainModelEditor.cs:line 345
   at Mendix.Modeler.Utility.AutoCanvas.canvas_Paint(Object sender, PaintEventArgs e) in C:\jenkins-ci\workspace\AppStudio3.0-Build\modeler\Mendix.Modeler.Utility.Gui\AutoCanvas.cs:line 357
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by RCatersels** [comment]
That is a known bug in 7.23.6. See the release notes of 7.23.7:
We fixed an error in the domain model editor that displayed a big red cross if associations had zero length. (Tickets 85602, 85421, 85308)
